version: "3.8"
services:
  srs-rtc-server:
    #image name
    image: shencoder/srs-rtc-server
    restart: always
    ports:
      #./config/config.yml--apiConfig.httpPort
      - "9898:9898"
      #./config/config.yml--apiConfig.httpsPort
      - "9899:9899"
      #./config/config.yml--socketIoConfig.httpPort
      - "9998:9998"
      #./config/config.yml--socketIoConfig.httpPort
      - "9999:9999"
    volumes:
      - .:/home/public/srs-rtc-server/
