version: "3.8"
services:
  srs-rtc-server:
    #image name
    #image: shencoder/srs-rtc-server
    #直接从Dockerfile构建
    build: .
    #自启
    restart: always
    #主机模式  network_mode: host 与 ports不兼容
    network_mode: host
    #端口
    #ports:
      #./config/config.yml--apiConfig.httpPort
      #- "9898:9898"
      #./config/config.yml--apiConfig.httpsPort
      #- "9899:9899"
      #./config/config.yml--socketIoConfig.httpPort
      #- "9998:9998"
      #./config/config.yml--socketIoConfig.httpPort
      #- "9999:9999"
    #挂载本地文件
    volumes:
      - ./cert:/home/public/srs-rtc-server/cert
      - ./config:/home/public/srs-rtc-server/config
      - ./src:/home/public/srs-rtc-server/src
      - ./app.js:/home/public/srs-rtc-server/app.js
      - ./package.json:/home/public/srs-rtc-server/package.json
      - ./package-lock.json:/home/public/srs-rtc-server/package-lock.json
      - ./yarn.lock:/home/public/srs-rtc-server/yarn.lock